/* PdfLens tests: shared engine over the corpus vs tests/expected.json
   (generated by oracle.py using real pypdf; raw-bytes checks independent). */
'use strict';
const fs=require('fs'),path=require('path');
const engine=require(path.join(__dirname,'..','engine.js'));
function load(p){
  if(fs.existsSync(p))return new Uint8Array(fs.readFileSync(p));
  const b=p+'.b64';
  if(fs.existsSync(b))return new Uint8Array(Buffer.from(fs.readFileSync(b,'utf8').trim(),'base64'));
  throw new Error('missing corpus '+p);
}
const items=JSON.parse(fs.readFileSync(path.join(__dirname,'expected.json'),'utf8')).items;
let fail=0,pass=0;
function eq(a,b,label){
  if(JSON.stringify(a)===JSON.stringify(b)){pass++;return;}
  fail++;console.log('FAIL '+label+': got '+JSON.stringify(a)+' want '+JSON.stringify(b));
}
for(const item of items){
  const bytes=load(path.join(__dirname,'corpus',item.file));
  const r=engine.parse(bytes);
  const T=item.file+' ';
  eq(r.version,item.version,T+'version');
  eq(r.has_eof,item.has_eof,T+'has_eof');
  eq(r.size,item.size,T+'size');
  if(item.expect_warning){
    if(r.warnings.some(w=>w.indexOf(item.expect_warning)>=0)){pass++;}
    else {fail++;console.log('FAIL '+T+'missing warning '+item.expect_warning+' (got '+JSON.stringify(r.warnings)+')');}
    continue;
  }
  eq(r.errors.length,0,T+'errors '+JSON.stringify(r.errors));
  eq(!!r.encrypted,item.encrypted,T+'encrypted');
  eq(r.pages,item.pages,T+'pages');
  eq(r.objects_gen0,item.objects_gen0,T+'objects_gen0');
  eq(r.pages_root_count,item.pages_root_count,T+'pages_root_count');
  if(!item.encrypted){
    for(const k of ['title','author','subject','keywords','creator','producer']){
      if(item[k]!==undefined)eq(r.meta[k],item[k],T+'meta.'+k);
    }
  } else {
    /* engine must not leak ciphertext as metadata */
    eq(Object.keys(r.meta).length,0,T+'encrypted meta suppressed');
  }
}
console.log(pass+' passed, '+fail+' failed');
process.exit(fail?1:0);
